server:
  connector:
    port: 18000
    type: http
  adminContextPath: /admin
  applicationContextPath: /
  type: simple


logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      logFormat: "restfire %d [%thread] %-5level %c{15} - %msg%n%rEx"

mongo:
  seeds:
  - host: ${MONGO_HOST}
    port: ${MONGO_PORT}
  database: restfire

workerThreads: 4
bigQueueFolderPath: ${BIGQUEUE_PATH}
bigQueueName: restfire
threadSleepTimeSec: 10
dropMessagePostMinutes: ${DROP_MESSAGE_POST_MINUTES}